#!/bin/sh
# Public Domain

# optional variables to set before sourcing this script
#
# - W_PULSEAUDIO_IS_OPTIONAL=yes [show --disable-pulse in --help msg]
# - W_PULSEAUDIO_MIN_VERSION=xxx [minimun supported version, .pc file is required]
#

#=======================================
w_new_option pulse PULSEAUDIO
#=======================================

pulse_pc_pkg="libpulse"


opt_print_pulse()
{
	if [ "$W_PULSEAUDIO_IS_OPTIONAL" = "yes" ] ; then
		echo "  --disable-pulse           do not build PULSEAUDIO support (autodetect)"
	fi
}


opt_configure_pulse()
{
	if [ "$W_PULSEAUDIO_IS_OPTIONAL" = "yes" ] ; then
		enable_pulse=check
	else
		enable_pulse=yes
		return
	fi

	for i in $@
	do
		case $i in
		--enable-pulse)  enable_pulse=yes ;;
		--disable-pulse) enable_pulse=no ;;
		esac
	done
}


opt_check_pulse()
{
	if [ "$enable_pulse" = "no" ] ; then
		return
	fi

	if [ -n "$PULSEAUDIO_CFLAGS" ] || [ -n "$PULSEAUDIO_LIBS" ] ; then
		echo "Checking for PULSEAUDIO... \$PULSEAUDIO_CFLAGS/\$PULSEAUDIO_LIBS"
	else
		pcpkg=
		for onepkg in ${pulse_pc_pkg}
		do
			if w_pkgconfig_check ${onepkg} ${W_PULSEAUDIO_MIN_VERSION} ; then
				pcpkg=${onepkg}
				break
			fi
		done

		if [ -z "$pcpkg" ] ; then
			if [ "$enable_pulse" = "yes" ] ; then
				exit_error "pkg-config: pulse was not found"
			fi
			return
		fi
		if [ ! -f "$pcpkg" ] ; then
			# $pcpkg must not be a file, otherwise it is a custom xxx-config file
			PULSEAUDIO_CFLAGS="$(run_pkg_config ${pcpkg} --cflags 2>/dev/null)"
			PULSEAUDIO_LIBS="$(run_pkg_config ${pcpkg} --libs 2>/dev/null)"
		fi
	fi

	config_h_have="$config_h_have PULSEAUDIO"
	config_mk_flags="$config_mk_flags PULSEAUDIO"
}

