#!/bin/sh
# Public Domain

# optional variables to set before sourcing this script
#
# - W_PULSEAUDIO_IS_OPTIONAL=yes [show --disable-pulse_glib in --help msg]
# - W_PULSEAUDIO_MIN_VERSION=xxx [minimun supported version, .pc file is required]
#

#=======================================
w_new_option pulse_glib PULSEAUDIO
#=======================================

pulse_glib_pc_pkg="libpulse-mainloop-glib"


opt_print_pulse_glib()
{
	if [ "$W_PULSEAUDIO_IS_OPTIONAL" = "yes" ] ; then
		echo "  --disable-pulse_glib           do not build PULSEAUDIO support (autodetect)"
	fi
}


opt_configure_pulse_glib()
{
	if [ "$W_PULSEAUDIO_IS_OPTIONAL" = "yes" ] ; then
		enable_pulse_glib=check
	else
		enable_pulse_glib=yes
		return
	fi

	for i in $@
	do
		case $i in
		--enable-pulse_glib)  enable_pulse_glib=yes ;;
		--disable-pulse_glib) enable_pulse_glib=no ;;
		esac
	done
}


opt_check_pulse_glib()
{
	if [ "$enable_pulse_glib" = "no" ] ; then
		return
	fi

	if [ -n "$PULSEAUDIO_CFLAGS" ] || [ -n "$PULSEAUDIO_LIBS" ] ; then
		echo "Checking for PULSEAUDIO... \$PULSEAUDIO_CFLAGS/\$PULSEAUDIO_LIBS"
	else
		pcpkg=
		for onepkg in ${pulse_glib_pc_pkg}
		do
			if w_pkgconfig_check ${onepkg} ${W_PULSEAUDIO_MIN_VERSION} ; then
				pcpkg=${onepkg}
				break
			fi
		done

		if [ -z "$pcpkg" ] ; then
			if [ "$enable_pulse_glib" = "yes" ] ; then
				exit_error "pkg-config: pulse_glib was not found"
			fi
			return
		fi
		if [ ! -f "$pcpkg" ] ; then
			# $pcpkg must not be a file, otherwise it is a custom xxx-config file
			PULSEAUDIO_CFLAGS="$(run_pkg_config ${pcpkg} --cflags 2>/dev/null)"
			PULSEAUDIO_LIBS="$(run_pkg_config ${pcpkg} --libs 2>/dev/null)"
		fi
	fi

	config_h_have="$config_h_have PULSEAUDIO"
	config_mk_flags="$config_mk_flags PULSEAUDIO"
}

